version: "3.8"
services:
  browser-use-poc:
    build: .
    container_name: browser-use-poc
    restart: "no"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
              # 如果还有其他需要从 .env 加载的变量，也用同样格式添加
              # - OPENAI_API_KEY=${OPENAI_API_KEY}
    # 可以添加volumes等配置