version: "3.8"
services:
  browser-use-poc:
    build: .
    container_name: browser-use-poc
    restart: "no"
    environment:
      - OPENROUTER_API_KEY=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
    # 可以添加volumes等配置